<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="refactoring"
    nsURI="http://refactoring/1.0" nsPrefix="refactoring">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//Method" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Refactoring" abstract="true" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="RenameFeature" eSuperTypes="#//Refactoring">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRefactorings" upperBound="-1"
        eType="#//RenameFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RenameClass" eSuperTypes="#//RenameFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classToBeRename" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classToBeRenamedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" eType="#//ElementType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BasicType" eSuperTypes="#//ElementType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassType" eSuperTypes="#//ElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classType" eType="#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RenameAttribute" eSuperTypes="#//RenameFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeToBeRename" eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceClass" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeToBeRenamedName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RenameMethod" eSuperTypes="#//RenameFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodToBeRename" eType="#//Method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceClass" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodToBeRenamedName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MovingFeaturesBetweenObjects" eSuperTypes="#//Refactoring">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRefactorings" upperBound="-1"
        eType="#//MovingFeaturesBetweenObjects" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoveAttribute" eSuperTypes="#//MovingFeaturesBetweenObjects">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceClass" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetClass" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeToBeMoved" eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeToBeMovedName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoveMethod" eSuperTypes="#//MovingFeaturesBetweenObjects">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceClass" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetClass" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodToBeMoved" eType="#//Method"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodToBeMovedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtractClass" eSuperTypes="#//MovingFeaturesBetweenObjects">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceClass" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributesToBeMoved" upperBound="-1"
        eType="#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InlineClass" eSuperTypes="#//MovingFeaturesBetweenObjects">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classToGetAllFeatures"
        eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classToRemove" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classToGetAllFeaturesName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classToRemoveName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrganizingData" eSuperTypes="#//Refactoring">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRefactorings" upperBound="-1"
        eType="#//OrganizingData" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReplaceDataValueWithObject" eSuperTypes="#//OrganizingData">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceClass" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeToReplaceDataWithObject"
        eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newAttributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EncapsulateField" eSuperTypes="#//OrganizingData">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceClass" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeToEncapsulate"
        eType="#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DealingWithGeneralization" eSuperTypes="#//Refactoring">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRefactorings" upperBound="-1"
        eType="#//DealingWithGeneralization" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PushDownMethod" eSuperTypes="#//DealingWithGeneralization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodToBePushed" eType="#//Method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceClass" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetClass" eType="#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PushDownAttribute" eSuperTypes="#//DealingWithGeneralization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeToBePushed" eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceClass" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetClass" eType="#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PullUpAttribute" eSuperTypes="#//DealingWithGeneralization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeToBePulled" eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceClass" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetClass" eType="#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PullUpMethod" eSuperTypes="#//DealingWithGeneralization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodToBePulled" eType="#//Method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceClass" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetClass" eType="#//Class"/>
  </eClassifiers>
</ecore:EPackage>
